import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from './_appComponents/SessionProvider'
import dbConnect from "../../mongoose/connect";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MusicAL",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  dbConnect();
  const serverSession=await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={serverSession}>
          {children}
        </SessionProvider>
        </body>
    </html>
  );
}
